---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: helm-toolkit
data:
  chart_name: helm-toolkit
  release: helm-toolkit
  namespace: helm-toolkit
  timeout: 100
  values: {}
  source:
    type: git
    location: https://github.com/openstack/openstack-helm
    subpath: helm-toolkit
    reference: master
  dependencies: []
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ceph
data:
  chart_name: ceph
  release: ceph
  namespace: ceph
  timeout: 3600
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
    pre:
      delete:
        - name: ceph-bootstrap
          type: job
          labels:
            - application: ceph
            - component: bootstrap
            - release_group: armada-ucp
        - name: ceph-mds-keyring-generator
          type: job
          labels:
            - application: ceph
            - component: mds-keyring-generator
            - release_group: armada-ucp
        - name: ceph-mon-keyring-generator
          type: job
          labels:
            - application: ceph
            - component: mon-keyring-generator
            - release_group: armada-ucp
        - name: ceph-rgw-keyring-generator
          type: job
          labels:
            - application: ceph
            - component: rgw-keyring-generator
            - release_group: armada-ucp
        - name: ceph-storage-keys-generator
          type: job
          labels:
            - application: ceph
            - component: storage-keys-generator
            - release_group: armada-ucp
        - name: ceph-osd-keyring-generator
          type: job
          labels:
            - application: ceph
            - component: osd-keyring-generator
            - release_group: armada-ucp
  values:
    labels:
      jobs:
        node_selector_key: ucp-control-plane
        node_selector_value: enabled
    endpoints:
      identity:
        namespace: ucp
      object_store:
        namespace: ceph
      ceph_mon:
        namespace: ceph
    ceph:
      rgw_keystone_auth: true
      storage:
        osd_directory: /var/lib/openstack-helm/ceph/osd
    network:
      public: 172.24.1.0/24
      cluster: 172.24.1.0/24
    deployment:
      storage_secrets: true
      ceph: true
      rbd_provisioner: true
      client_secrets: false
      rgw_keystone_user_and_endpoints: false
    bootstrap:
      enabled: true
  source:
    type: git
    location: https://github.com/openstack/openstack-helm
    subpath: ceph
    reference: master
  dependencies:
    - helm-toolkit
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-ceph-config
data:
  chart_name: ucp-ceph-config
  release: ucp-ceph-config
  namespace: ucp
  timeout: 3600
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
    pre:
      delete:
        - name: ceph-namespace-client-key-generator
          type: job
          labels:
            - application: ceph
            - component: namespace-client-key-generator
            - release_group: armada-ucp
  values:
    labels:
      jobs:
        node_selector_key: ucp-control-plane
        node_selector_value: enabled
    endpoints:
      identity:
        namespace: ucp
      object_store:
        namespace: ceph
      ceph_mon:
        namespace: ceph
    ceph:
      rgw_keystone_auth: true
    network:
      public: 172.24.1.0/24
      cluster: 172.24.1.0/24
    deployment:
      storage_secrets: false
      ceph: false
      rbd_provisioner: false
      client_secrets: true
      rgw_keystone_user_and_endpoints: false
  source:
    type: git
    location: https://github.com/openstack/openstack-helm
    subpath: ceph
    reference: master
  dependencies:
    - helm-toolkit
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-mariadb
data:
  chart_name: ucp-mariadb
  release: ucp-mariadb
  namespace: ucp
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  values:
    labels:
      node_selector_key: ucp-control-plane
      node_selector_value: enabled
    replicas:
      server: 1
  source:
    type: git
    location: https://git.openstack.org/openstack/openstack-helm
    subpath: mariadb
  dependencies:
    - helm-toolkit
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-memcached
data:
  chart_name: ucp-memcached
  release: ucp-memcached
  namespace: ucp
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  values:
    labels:
      node_selector_key: ucp-control-plane
      node_selector_value: enabled
  source:
    type: git
    location: https://git.openstack.org/openstack/openstack-helm
    subpath: memcached
  dependencies:
    - helm-toolkit
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-keystone
data:
  chart_name: ucp-keystone
  release: keystone
  namespace: ucp
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  pre:
    delete:
      - name: keystone-db-sync
        type: job
        labels:
          - job-name: keystone-db-sync
      - name: keystone-db-init
        type: job
        labels:
          - job-name: keystone-db-init
  post:
    delete: []
    create: []
  values:
    conf:
      keystone:
        override:
      paste:
        override:
    replicas: 2
    labels:
      node_selector_key: ucp-control-plane
      node_selector_value: enabled
  source:
    type: git
    location: https://git.openstack.org/openstack/openstack-helm
    subpath: keystone
  dependencies:
    - helm-toolkit
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: maas-postgresql
data:
  chart_name: maas-postgresql
  release: maas-postgresql
  namespace: ucp
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  pre:
    delete: []
    create: []
  post:
    delete: []
    create: []
  values:
    development:
      enabled: false
    labels:
      node_selector_key: ucp-control-plane
      node_selector_value: enabled
  source:
    type: git
    location: https://git.openstack.org/openstack/openstack-helm
    subpath: postgresql
    reference: master
  dependencies:
    - helm-toolkit
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: maas
data:
  chart_name: maas
  release: maas
  namespace: ucp
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  values:
    bootdata_url: http://172.24.1.100:31000/api/v1.0/bootdata/
    labels:
      rack:
        node_selector_key: ucp-control-plane
        node_selector_value: enabled
      region:
        node_selector_key: ucp-control-plane
        node_selector_value: enabled
    network:
      proxy:
        node_port:
          enabled: true
          port: 31800
      gui:
        node_port:
          enabled: true
          port: 31900
    conf:
      maas:
        credentials:
          secret:
            namespace: ucp
        url:
          maas_url: http://172.24.1.100:31900/MAAS
        proxy:
          proxy_enabled: 'false'
          proxy_server: http://one.proxy.att.com:8080
        ntp:
          use_external_only: 'false'
          ntp_servers: ntp.ubuntu.com
        dns:
          require_dnssec: 'no'
          dns_servers: 8.8.8.8
    secrets:
      maas_region:
        value: 3858a12230ac3c915f300c664f12063f
  source:
    type: git
    location: https://github.com/att-comdev/maas
    subpath: charts/maas
    reference: refs/changes/79/384379/1
  dependencies:
    - helm-toolkit
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: drydock
data:
  chart_name: drydock
  release: drydock
  namespace: ucp
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  values:
    images:
      tags:
        drydock: docker.io/sthussey/drydock:384384v1
        drydock_db_sync: docker.io/sthussey/drydock:384384v1
    labels:
      node_selector_key: ucp-control-plane
      node_selector_value: enabled
    network:
      drydock:
        node_port:
          enabled: true
    endpoints:
      physicalprovisioner:
        port:
          api:
            nodeport: 31000
    conf:
      drydock:
        maasdriver:
          maas_api_url: http://172.24.1.100:31900/MAAS/api/2.0/
  source:
    type: git
    location: https://github.com/att-comdev/drydock
    subpath: charts/drydock
    reference: master
  dependencies:
    - helm-toolkit
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: deckhand
data:
  chart_name: deckhand
  release: deckhand
  namespace: ucp
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  values:
    images:
      deckhand: quay.io/attcomdev/deckhand:master
    labels:
      node_selector_key: ucp-control-plane
      node_selector_value: enabled
    conf:
      deckhand:
        DEFAULT:
          debug: true
          use_stderr: true
          use_syslog: true
  source:
    type: git
    location: https://github.com/att-comdev/deckhand
    subpath: charts/deckhand
    reference: master
  dependencies:
    - helm-toolkit
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-barbican
data:
  chart_name: ucp-barbican
  release: barbican
  namespace: ucp
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  pre:
    delete: []
  post:
    delete: []
    create: []
  values:
    images:
      tags:
        api: docker.io/kolla/ubuntu-source-barbican-api:3.0.3
        db_sync: docker.io/kolla/ubuntu-source-barbican-api:3.0.3
        test: docker.io/kolla/ubuntu-source-heat-engine:3.0.3
    pod:
      replicas:
        api: 1
    labels:
      node_selector_key: ucp-control-plane
      node_selector_value: enabled
  source:
    type: git
    location: https://git.openstack.org/openstack/openstack-helm
    subpath: barbican
  dependencies:
    - helm-toolkit
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: shipyard
data:
  chart_name: shipyard
  release: shipyard
  namespace: ucp
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  values:
    prod_environment: true
    images:
      airflow: quay.io/attcomdev/airflow:master
      shipyard: quay.io/attcomdev/shipyard:master
      airflow_db_sync: quay.io/attcomdev/airflow:master
    labels:
      node_selector_key: ucp-control-plane
      node_selector_value: enabled
    network:
      shipyard:
        node_port: 31901
        enable_node_port: true
      airflow:
        web:
          node_port: 32080
          enable_node_port: true
    conf:
      shipyard:
        keystone_authtoken:
          memcache_security_strategy: None
  source:
    type: git
    location: https://github.com/att-comdev/shipyard
    subpath: charts/shipyard
    reference: master
  dependencies:
    - helm-toolkit
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: armada
data:
  chart_name: armada
  release: armada
  namespace: ucp
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  values:
    images:
      tags:
        api: quay.io/attcomdev/armada:v0.7.0
    labels:
      node_selector_key: ucp-control-plane
      node_selector_value: enabled
    network:
      api:
        node_port:
          enabled: true
          port: 31903
  source:
    type: git
    location: https://github.com/att-comdev/armada
    subpath: charts/armada
    reference: master
  dependencies:
    - helm-toolkit
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-etcd-rabbitmq
data:
  chart_name: ucp-etcd-rabbitmq
  release: etcd-rabbitmq
  namespace: ucp
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  pre:
    delete: []
  post:
    delete: []
    create: []
  values:
    pod:
      replicas:
        etcd: 1
    labels:
      node_selector_key: ucp-control-plane
      node_selector_value: enabled
  source:
    type: git
    location: https://git.openstack.org/openstack/openstack-helm
    subpath: etcd
  dependencies:
    - helm-toolkit
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-rabbitmq
data:
  chart_name: ucp-rabbitmq
  release: rabbitmq
  namespace: ucp
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  pre:
    delete: []
  post:
    delete: []
    create: []
  values:
    pod:
      replicas:
        server: 1
    labels:
      node_selector_key: ucp-control-plane
      node_selector_value: enabled
  source:
    type: git
    location: https://git.openstack.org/openstack/openstack-helm
    subpath: rabbitmq
  dependencies:
    - helm-toolkit
---
schema: armada/Manifest/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-basic
data:
  release_prefix: armada-ucp
  chart_groups:
    - ceph
    - ucp-infra
    - ucp-services
---
schema: armada/ChartGroup/v1
metadata:
  schema: metadata/Document/v1
  name: ceph
data:
  description: 'Storage Backend'
  sequenced: true
  chart_group:
    - ceph
    - ucp-ceph-config
---
schema: armada/ChartGroup/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-infra
data:
  description: 'UCP Infrastructure'
  chart_group:
    - ucp-mariadb
    - ucp-memcached
    - maas-postgresql
    - ucp-etcd-rabbitmq
    - ucp-rabbitmq
---
schema: armada/ChartGroup/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-services
data:
  description: 'UCP Services'
  chart_group:
    - maas
    - drydock
    - deckhand
    - shipyard
    - armada
    - ucp-keystone
    - ucp-barbican
...
