---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: helm-toolkit
data:
  chart_name: helm-toolkit
  release: helm-toolkit
  namespace: helm-toolkit
  timeout: 100
  values: {}
  source:
    type: git
    location: git://git.openstack.org/openstack/openstack-helm
    subpath: helm-toolkit
    reference: master
  dependencies: []
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ceph
data:
  chart_name: ceph
  release: ceph
  namespace: ceph
  timeout: 3600
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  values:
    manifests_enabled:
      client_secrets: False
    bootstrap:
      enabled: True
    network:
      public: 172.20.0.0/24
      cluster: 172.20.0.0/24
    conf:
      ceph:
        config:
          global:
            osd_pool_default_size: 1
          osd:
            osd_crush_chooseleaf_type: 0
  source:
    type: git
    location: git://git.openstack.org/openstack/openstack-helm
    subpath: ceph
    reference: master
  dependencies:
    - helm-toolkit
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-ceph-config
data:
  chart_name: ucp-ceph-config
  release: ucp-ceph-config
  namespace: ucp
  timeout: 3600
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  values:
    ceph:
      namespace: ceph
    manifests_enabled:
      deployment: False
      storage_secrets: False
    network:
      public: 172.20.0.0/24
      cluster: 172.20.0.0/24
  source:
    type: git
    location: git://git.openstack.org/openstack/openstack-helm
    subpath: ceph
    reference: master
  dependencies:
    - helm-toolkit
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: maas-ceph-config
data:
  chart_name: maas-ceph-config
  release: maas-ceph-config
  namespace: maas
  timeout: 3600
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  values:
    ceph:
      namespace: ceph
    manifests_enabled:
      deployment: False
      storage_secrets: False
    network:
      public: 172.20.0.0/24
      cluster: 172.20.0.0/24
  source:
    type: git
    location: git://git.openstack.org/openstack/openstack-helm
    subpath: ceph
    reference: master
  dependencies:
    - helm-toolkit
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-mariadb
data:
  chart_name: ucp-mariadb
  release: ucp-mariadb
  namespace: ucp
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  values:
    labels:
      node_selector_key: ucp-control-plane
      node_selector_value: enabled
  source:
    type: git
    location: git://git.openstack.org/openstack/openstack-helm
    subpath: mariadb
  dependencies:
    - helm-toolkit
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-memcached
data:
  chart_name: ucp-memcached
  release: ucp-memcached
  namespace: ucp
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  values:
    labels:
      node_selector_key: ucp-control-plane
      node_selector_value: enabled
  source:
    type: git
    location: git://git.openstack.org/openstack/openstack-helm
    subpath: memcached
  dependencies:
    - helm-toolkit
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-keystone
data:
  chart_name: ucp-keystone
  release: keystone
  namespace: ucp
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  pre:
    delete:
      - name: keystone-db-sync
        type: job
        labels:
          - job-name: keystone-db-sync
      - name: keystone-db-init
        type: job
        labels:
          - job-name: keystone-db-init
  post:
    delete: []
    create: []
  values:
    conf:
      keystone:
        override: |+
          # Copyright 2017 The Openstack-Helm Authors.
          #
          # Licensed under the Apache License, Version 2.0 (the "License");
          # you may not use this file except in compliance with the License.
          # You may obtain a copy of the License at
          #
          #     http://www.apache.org/licenses/LICENSE-2.0
          #
          # Unless required by applicable law or agreed to in writing, software
          # distributed under the License is distributed on an "AS IS" BASIS,
          # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
          # See the License for the specific language governing permissions and
          # limitations under the License.

          [DEFAULT]
          use_syslog = False
          use_stderr = True

          [database]
          connection = mysql+pymysql://keystone:password@mariadb/keystone
          max_retries = -1

          [memcache]
          servers = memcached:11211

          [token]
          provider = uuid

          [cache]
          backend = dogpile.cache.memcached
          memcache_servers = memcached:11211
          config_prefix = cache.keystone
          enabled = True
      paste:
        override: |+
          # Keystone PasteDeploy configuration file.

          [filter:debug]
          use = egg:oslo.middleware#debug

          [filter:request_id]
          use = egg:oslo.middleware#request_id

          [filter:build_auth_context]
          use = egg:keystone#build_auth_context

          [filter:token_auth]
          use = egg:keystone#token_auth

          [filter:admin_token_auth]
          # This is deprecated in the M release and will be removed in the O release.
          # Use `keystone-manage bootstrap` and remove this from the pipelines below.
          use = egg:keystone#admin_token_auth

          [filter:json_body]
          use = egg:keystone#json_body

          [filter:cors]
          use = egg:oslo.middleware#cors
          oslo_config_project = keystone

          [filter:ec2_extension]
          use = egg:keystone#ec2_extension

          [filter:ec2_extension_v3]
          use = egg:keystone#ec2_extension_v3

          [filter:s3_extension]
          use = egg:keystone#s3_extension

          [filter:url_normalize]
          use = egg:keystone#url_normalize

          [filter:sizelimit]
          use = egg:oslo.middleware#sizelimit

          [app:public_service]
          use = egg:keystone#public_service

          [app:service_v3]
          use = egg:keystone#service_v3

          [app:admin_service]
          use = egg:keystone#admin_service

          [pipeline:public_api]
          # The last item in this pipeline must be public_service or an equivalent
          # application. It cannot be a filter.
          pipeline = cors sizelimit url_normalize request_id admin_token_auth build_auth_context token_auth json_body ec2_extension public_service

          [pipeline:admin_api]
          # The last item in this pipeline must be admin_service or an equivalent
          # application. It cannot be a filter.
          pipeline = cors sizelimit url_normalize request_id admin_token_auth build_auth_context token_auth json_body ec2_extension s3_extension admin_service

          [pipeline:api_v3]
          # The last item in this pipeline must be service_v3 or an equivalent
          # application. It cannot be a filter.
          pipeline = cors sizelimit url_normalize request_id admin_token_auth build_auth_context token_auth json_body ec2_extension_v3 s3_extension service_v3

          [app:public_version_service]
          use = egg:keystone#public_version_service

          [app:admin_version_service]
          use = egg:keystone#admin_version_service

          [pipeline:public_version_api]
          pipeline = cors sizelimit url_normalize public_version_service

          [pipeline:admin_version_api]
          pipeline = cors sizelimit url_normalize admin_version_service

          [composite:main]
          use = egg:Paste#urlmap
          /v2.0 = public_api
          /v3 = api_v3
          / = public_version_api

          [composite:admin]
          use = egg:Paste#urlmap
          /v2.0 = admin_api
          /v3 = api_v3
          / = admin_version_api
    replicas: 2
    images:
      db_sync: kolla/ubuntu-source-keystone:2.0.2
      api: kolla/ubuntu-source-keystone:2.0.2
    labels:
      node_selector_key: ucp-control-plane
      node_selector_value: enabled
  source:
    type: git
    location: git://git.openstack.org/openstack/openstack-helm
    subpath: keystone
  dependencies:
    - helm-toolkit
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: maas-postgresql
data:
  chart_name: maas-postgresql
  release: maas-postgresql
  namespace: maas
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  pre:
    delete: []
    create: []
  post:
    delete: []
    create: []
  values:
    development:
      enabled: false
    labels:
      node_selector_key: ucp-control-plane
      node_selector_value: enabled
  source:
    type: git
    location: git://git.openstack.org/openstack/openstack-helm-addons
    subpath: postgresql
  dependencies: []
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: maas
data:
  chart_name: maas
  release: maas
  namespace: maas
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  pre:
    delete: []
    create: []
  post:
    delete: []
    create: []
  values:
    bootdata_url: http://10.23.19.118:31000/api/v1.0/bootdata/
    credentials:
      secret:
        namespace: drydock
    images:
      maas_rack: quay.io/attcomdev/maas-rack:2.2.0-no-ipmi-patch
    labels:
      node_selector_key: ucp-control-plane
      node_selector_value: enabled
    network:
      proxy:
        node_port:
          enabled: true
          port: 31800
      gui:
        node_port:
          enabled: true
          port: 31900
    conf:
      maas:
        url: http://10.23.19.118:31900/MAAS
        proxy:
          enabled: 'false'
          server: http://one.proxy.att.com:8080
        ntp:
          servers: ntp.ubuntu.com
        dns:
          upstream_servers: 8.8.8.8
      secret: 3858a12230ac3c915f300c664f12063f
  source:
    type: local
    location: /opt/armada/charts
    subpath: maas
  dependencies:
    - helm-toolkit
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: drydock
data:
  chart_name: drydock
  release: drydock
  namespace: ucp
  install:
    no_hooks: false
  upgrade:
    no_hooks: false
  pre:
    delete: []
    create: []
  post:
    delete: []
    create: []
  values:
    images:
      drydock: quay.io/attcomdev/drydock:feature_DRYD19_keystone_middleware_integration
    labels:
      node_selector_key: ucp-control-plane
      node_selector_value: enabled
    network:
      drydock:
        node_port:
          enabled: true
          port: 31000
    conf:
      drydock:
        maasdriver:
          drydock_provisioner:
            maas_api_url: http://172.20.0.12:31900/MAAS/api/2.0/
  source:
    type: local
    location: /opt/armada/charts
    subpath: drydock
  dependencies:
    - helm-toolkit
---
schema: armada/Manifest/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-basic
data:
  release_prefix: armada-ucp
  chart_groups:
    - ucp-infra
    - ucp-services
---
schema: armada/ChartGroup/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-infra
data:
  description: 'UCP Infrastructure'
  chart_group:
    - ceph
    - ucp-mariadb
    - ucp-memcached
    - ucp-keystone
    - maas-postgresql
---
schema: armada/ChartGroup/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-services
data:
  description: 'UCP Services'
  chart_group:
    - maas
    - drydock
...
