---
schema: armada/ChartGroup/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-storage-provisioner
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
data:
  description: Kubernetes Storage Provisioner
  chart_group:
    - ucp-storage-provisioner
