---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-storage-provisioner
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.ucp.nfs_provisioner
      dest:
        path: .source

    # Images
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .images.storage.nfs_provisioner
      dest:
        path: .values.images.tags
data:
  chart_name: nfs-provisioner
  release: nfs-provisioner
  namespace: kube-system
  timeout: 900
  wait:
    timeout: 900
  install:
    no_hooks: false
  upgrade:
    no_hooks: true
  values:
    labels:
      nfs:
        node_selector_key: ucp-control-plane
        node_selector_value: enabled
      job:
        node_selector_key: ucp-control-plane
        node_selector_value: enabled
    storage:
      hostPath:
        path: /var/lib/airship/nfs
      persistentVolumeClaim:
        size: '30Gi'
    manifests:
      job_image_repo_sync: false
  dependencies:
    - nfs_htk
...
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: nfs_htk
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.ucp.nfs-htk
      dest:
        path: .source
data:
  chart_name: nfs_htk
  release: nfs_htk
  namespace: nfs_htk
  timeout: 100
  values: {}
  dependencies: []
...
