---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: coredns
  layeringDefinition:
    abstract: false
    layer: global
  labels:
    name: coredns
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.kubernetes.coredns
      dest:
        path: .source

    # Images
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .images.kubernetes.coredns
      dest:
        path: .values.images
data:
  chart_name: coredns
  release: coredns
  namespace: kube-system
  timeout: 600
  wait:
    timeout: 600
  upgrade:
    no_hooks: true
  dependencies:
    - coredns-htk
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: coredns-htk
  layeringDefinition:
    abstract: false
    layer: global
  storagePolicy: cleartext
  substitutions:
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.kubernetes.coredns-htk
      dest:
        path: .source
data:
  chart_name: coredns-htk
  release: coredns-htk
  namespace: coredns-htk
  timeout: 100
  values: {}
  dependencies: []
...
